sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: EG7E0jV0AoRe7JTey6qRNDg+1iz0R7EpHK71UA6ciYCRhlXC43Jd3XDbjL9FFmmjy+Updx1d1j3wipHEDgXCljTdSt6Vvp4Sd8odFwrV0ExTdWFLDC7vOmzj4Z3owfyIQbdFb4iNsq0N/vnOqi6ayxxJHHT+IZbyrS5ViZhemsZMOsdHrV+sSNB/hgSanvFyTWKwPUS5MfFJPhC6BUcGcPOd9O3jjM5wdtoIS042as4jkQqM08w8GyEf8RXL0PotOBuYWCSZ6tgovWmSgAYV5g2LthFrEzyjUwiDSWyBCzUvghaRmh3xvUXq2VxdbwKVFMCxw8KK9PHQkGTZai0HmOSBJacJlPt8bsez2n/r4kz/6TJ9GYYVuwOHpG+xLd+22UI/fgwmJi2/gUNYngmtpouRICIVdNFpt15vtHWd3fcbsPAsXHMMgcITgIdH55JL+L1CxcWm43nuTkWfP5BSdQt38Vpknk3QXSHKdFaCsD6jK3+LjzY30yC/WlEzPgm5vDOF0TI2CS6SFmgnHLEMvFS4OzuzMT9GvXPlEIJ0Y7xC5l5gvGIyO4eGMflStUq5971oZKgRDIctf6dX7WMAMpSsE+BOKaNWq0/g02LnaIF3NRUJlsjBS7gcnKP9khI/4H+5uxrMGRLEuF3bkn7f8mbJ0FG6xb1+sEZDRCL2Vdg=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-1991-CIA-World-Factbook_25
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy